### ISSUE TITLE
Academic consult

### ISSUE THREAD

**Issue by ghost** [arturjordao/arturjordao.github.io#1]
Dear Artur,
    Hi,  I have read your paper "On the Effect of Pruning on Adversarial Robustness". I am very interested in this article and believe it will help a lot with my recent research. But I do not find it here, could you please release the code.

**Comment by arturjordao** [comment]
Dear @AllenPeng-libra,

I did not release the source code since I employed adversarial attacks and pruned models available at other GitHub repositories.  However, I have attached ([CodePaperICCV.zip](https://github.com/arturjordao/arturjordao.github.io/files/7553567/CodePaperICCV.zip)) examples employed throughout the experiments, for which you can reproduce the main findings of our paper. 

Importantly, on the semantic-preserving attack, you need to download the corrupted images (CIFAR-C) at this link: https://zenodo.org/record/2535967#.YEPqamhKjIU
After downloading the data, unzip them and set the "--corruption_path" (line 17 in semantic.py) by the path where the .npy files are.

I hope this helps your research.
Best Regards,
Artur Jordão.

**Comment by ghost** [comment]
Sorry, no code was found in the zip file.

**Comment by arturjordao** [comment]
Dear @AllenPeng-libra,

Try this file 
[CodePaperICCV.zip](https://github.com/arturjordao/arturjordao.github.io/files/7553557/CodePaperICCV.zip)
